# Generated by Django 4.2.2 on 2023-07-01 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.IntegerField()),
                ('message', models.CharField(max_length=200)),
                ('date', models.DateField(default=datetime.date(2023, 7, 1))),
                ('sent', models.BooleanField(default=False)),
            ],
        ),
    ]
